// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/card/random": {
            "get": {
                "description": "Returns a random card from a fresh, unsaved deck.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get a random card",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deck.Card"
                        }
                    }
                }
            }
        },
        "/deck": {
            "post": {
                "description": "Creates a new 52-card deck, persists it to disk, and returns its id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Create a new deck",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deck/{id}": {
            "get": {
                "description": "Returns the full stored deck for the given id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Get a stored deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deck.Card"
                            }
                        }
                    },
                    "404": {
                        "description": "deck not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deck/{id}/card/random": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Get a random card from a stored deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deck.Card"
                        }
                    },
                    "404": {
                        "description": "deck not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deck/{id}/card/top": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Get the top card of a stored deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deck.Card"
                        }
                    },
                    "400": {
                        "description": "deck is empty",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "deck not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deck/{id}/deal": {
            "post": {
                "description": "Deals handSize cards off the top of the stored deck. The stored deck shrinks by handSize.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Deal cards from a stored deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of cards to deal",
                        "name": "handSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deck.Card"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid handSize or handSize exceeds deck size",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "deck not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deck/{id}/shuffle": {
            "post": {
                "description": "Shuffles the stored deck in place and returns the shuffled deck.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "decks"
                ],
                "summary": "Shuffle a stored deck",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deck ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deck.Card"
                            }
                        }
                    },
                    "404": {
                        "description": "deck not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "deck.Card": {
            "type": "object",
            "properties": {
                "suit": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "go-cards API",
	Description:      "A small HTTP API for creating, persisting, and manipulating decks of cards.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
